package ${entity.packageName};

import lombok.Data;
<#if swagger>
import io.swagger.annotations.ApiModelProperty;
import io.swagger.annotations.ApiModel;
</#if>
<#list entity.javaTypeSet as javaType>
import ${javaType};
</#list>

/**
 * 〈功能详细描述〉
 * Generated by coco-builder
 *
 * @author ${author}
 */
@Data
<#if swagger>
@ApiModel("${entity.name}")
</#if>
public class ${entity.name} {

<#-- 循环类型及属性 -->
<#list entity.fields as attr>
    /**
     * ${attr.comment!attr.name}
     */
<#if swagger>
    @ApiModelProperty("${attr.comment!attr.name}")
</#if>
    private ${attr.javaType} ${attr.field};

</#list>


}